spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pw
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop                     # Create tables if not exist
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true       # CreateClob exception in current version





